#! /bin/sh

wm_startup

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme     spiral

bspc config presel_feedback_color "#2a2829"